### ISSUE TITLE
AttributeError: 'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by Zeronfinity** [cerob/slicesim#6]
```
C:\Users\Asus\Desktop\slicesim-master\slicesim-master> python -m slicesim ..\examples\istanbul-kapalicarsi.yml

Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\slicesim-master\slicesim-master\slicesim\Client.py", line 84, in iter
    self.assign_closest_base_station()
  File "C:\Users\Asus\Desktop\slicesim-master\slicesim-master\slicesim\Client.py", line 171, in assign_closest_base_station
    KDTree.run(self.stat_collector.clients, self.stat_collector.base_stations, int(self.env.now), assign=False)
  File "C:\Users\Asus\Desktop\slicesim-master\slicesim-master\slicesim\utils.py", line 36, in run
    tree = kdt(bs_coor, leaf_size=2)
  File "sklearn\neighbors\binary_tree.pxi", line 1068, in sklearn.neighbors.kd_tree.BinaryTree.__init__
AttributeError: 'list' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Asus\Desktop\slicesim-master\slicesim-master\slicesim\Client.py", line 88, in iter
    yield self.env.process(self.iter())
AttributeError: 'list' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Asus\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Asus\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Asus\Desktop\slicesim-master\slicesim-master\slicesim\__main__.py", line 151, in <module>
    env.run(until=int(SETTINGS['simulation_time']))
  File "C:\Users\Asus\Anaconda3\lib\site-packages\simpy\core.py", line 138, in run
    self.step()
  File "C:\Users\Asus\Anaconda3\lib\site-packages\simpy\core.py", line 230, in step
    raise exc
AttributeError: 'list' object has no attribute 'size'

```

**Comment by cerob** [comment]
Did you install the required libraries written in `requirements.txt`?

**Comment by Zeronfinity** [comment]
> Did you install the required libraries written in `requirements.txt`?

Yes. Here is a list of the packages along with the versions installed in my system.

Package                            Version
---------------------------------- ---------
cycler                             0.10.0
kiwisolver                         1.1.0
matplotlib                         3.1.1
numpy                              1.16.5
Pillow                             6.2.0
pyparsing                          2.4.2
python-dateutil                    2.8.0
PyYAML                             5.1.2
randomcolor                        0.4.4.5
scikit-learn                       0.21.3
scipy                              1.3.1
simpy                              3.0.11
six                                1.12.0
sklearn                            0.0

**Comment by Zeronfinity** [comment]
I made a virtual environment and installed the packages with exact versions written in `requirements.txt` and it worked fine.
