### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by rijilrose** [cerob/slicesim#8]
when we give sudo python3.7 -m slicesim istanbul-kapalicarsi.yml

Traceback (most recent call last):
  File "/home/antony/slicesim/slicesim-master/slicesim/Client.py", line 84, in iter
    self.assign_closest_base_station()
  File "/home/antony/slicesim/slicesim-master/slicesim/Client.py", line 171, in assign_closest_base_station
    KDTree.run(self.stat_collector.clients, self.stat_collector.base_stations, int(self.env.now), assign=False)
  File "/home/antony/slicesim/slicesim-master/slicesim/utils.py", line 36, in run
    tree = kdt(bs_coor, leaf_size=2)
  File "sklearn/neighbors/_binary_tree.pxi", line 1050, in sklearn.neighbors._kd_tree.BinaryTree.__init__
AttributeError: 'list' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/antony/slicesim/slicesim-master/slicesim/Client.py", line 88, in iter
    yield self.env.process(self.iter())
AttributeError: 'list' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/antony/slicesim/slicesim-master/slicesim/__main__.py", line 151, in <module>
    env.run(until=int(SETTINGS['simulation_time']))
  File "/usr/local/lib/python3.7/site-packages/simpy/core.py", line 254, in run
    self.step()
  File "/usr/local/lib/python3.7/site-packages/simpy/core.py", line 206, in step
    raise exc
AttributeError: 'list' object has no attribute 'size'

**Comment by punidramesh** [comment]
Create a virtualenv with Python 3.7 and install the requirements from the requirements.txt

Checkout : https://github.com/punidramesh/5g-network-slicing

**Comment by maykoonrenan** [comment]
> Create a virtualenv with Python 3.7 and install the requirements from the requirements.txt
> 
> Checkout : https://github.com/punidramesh/5g-network-slicing


Traduzir do: Inglês
2030/5000
I used the program from the link you left here (https://github.com/punidramesh/5g-network-slicing)e followed the steps you talked about, but I got the same errors. Here are the errors below:

(5g-network-slicing-master) (base) root @ maykon: / home / maykon / 5g-network-slicing-master / src # python -m slicesim network1.yml
Traceback (most recent call last):
  File "/home/maykon/5g-network-slicing-master/src/slicesim/Client.py", line 84, in iter
    self.assign_closest_base_station ()
  File "/home/maykon/5g-network-slicing-master/src/slicesim/Client.py", line 171, in assign_closest_base_station
    KDTree.run (self.stat_collector.clients, self.stat_collector.base_stations, int (self.env.now), assign = False)
  File "/home/maykon/5g-network-slicing-master/src/slicesim/utils.py", line 36, in run
    tree = kdt (bs_coor, leaf_size = 2)
  File "sklearn / neighbors / _binary_tree.pxi", line 1050, in sklearn.neighbors._kd_tree.BinaryTree .__ init__
AttributeError: 'list' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/maykon/5g-network-slicing-master/src/slicesim/Client.py", line 88, in iter
    yield self.env.process (self.iter ())
AttributeError: 'list' object has no attribute 'size'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec (code, run_globals)
  File "/home/maykon/5g-network-slicing-master/src/slicesim/__main__.py", line 151, in <module>
    env.run (until = int (SETTINGS ['simulation_time']))
  File "/home/maykon/5g-network-slicing-master/lib/python3.7/site-packages/simpy/core.py", line 138, in run
    self.step ()
  File "/home/maykon/5g-network-slicing-master/lib/python3.7/site-packages/simpy/core.py", line 230, in step
    raise exc
AttributeError: 'list' object has no attribute 'size'

**Comment by PrP-11** [comment]
@maykoonrenan I am also facing the same issue. Did you find a fix for it.

**Comment by cerob** [comment]
> @maykoonrenan I am also facing the same issue. Did you find a fix for it.

There is nothing broken and no fix is required to run. Just do install required libraries.

**Comment by HninPannPhyu** [comment]
I have come across the exact same error as @maykoonrenan . May i know how to fix it?
I have installed all the required libraries from requirements.txt.
